version: '3.8'

services:
  mysql: # See Also: https://hub.docker.com/_/mysql
    image: mysql:8.0.22
    platform: linux/amd64
    hostname: hostname-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classum
    ports:
      - 3306:3306
