version: '3.8'

services:
  mysql: # See Also: https://hub.docker.com/_/mysql
    container_name: ${DATABASE_HOSTNAME}
    image: mysql:8.0.22
    platform: linux/amd64
    hostname: ${DATABASE_HOSTNAME}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

